### ISSUE TITLE
Error when opening man page

### ISSUE THREAD

**Issue by lervag** [nhooyr/neoman.vim#1]
Hi. I'm trying out neoman now. I get this error when I try to open a man page with `:Neoman printf`:

```
Error detected while processing function neoman#get_page:
line   50:
E172: Only one file name allowed: edit man://printf(25               January 201
6                        PRINTF(1)
```

I use the following minimal vimrc file:

``` vim
set nocompatible
let &rtp = '~/.vim/bundle/neoman.vim,' . &rtp
filetype plugin indent on
syntax enable
```

I'm on a recently updated Arch Linux with vim/gvim version 7.4.1294.

**Comment by lervag** [comment]
For what it's worth, when I try to issue the command `/usr/bin/man -d printf`, I get a lot of noise in the terminal, then the manual page for `printf` is opened.

**Comment by lervag** [comment]
I'm wondering, should it be `/usr/bin/man -w ...` instead? I think the problem is [line 37](https://github.com/nhooyr/neoman.vim/commit/f7a63e61937fe8f3d53d413e1b1fba07b2da1b92#diff-04873a40c8356f8734b7019228076f4eL37), which was changed in the most recent commit.

**Comment by nhooyr** [comment]
Ahah I got it, I'll fix it. I've reverted that commit for now. Its just different behaviour on OSX and Linux.

**Comment by lervag** [comment]
Ok, I see. Looking forward to trying the plugin when things work. :)

**Comment by nhooyr** [comment]
@lervag I've got an idea to fix this. That line is for when the section is not provided and we need to determine it to name the buffer opened properly. Gotta get the one `man` will use. 

I'll add in linux support but in order to prevent unforeseen problems due to this, if the man page cannot be found after that line which is trying to determine it, `let sect = ''`. Perhaps even a message to open an issue so that I can investigate.

**Comment by nhooyr** [comment]
Screw that, you're right, I don't know how I missed the `-w` flag. I am using it to create the `$MANPATH` in the autocomplete and I thought thats all it did, I should have probably reread the option description, sigh. I'll add it in asap.

**Comment by nhooyr** [comment]
#6 should fix this, further discussion there.

**Comment by lervag** [comment]
Thanks!
