### ISSUE TITLE
`set keywordprg=:Nman` does not work

### ISSUE THREAD

**Issue by lervag** [nhooyr/neoman.vim#10]
As subject says: For me `set kp=:Nman` does not work as expected. I think this might be the standard Vim behaviour, though...

**Comment by nhooyr** [comment]
@lervag what do you mean it does not work. What happens?

**Comment by lervag** [comment]
To reproduce, I open a fresh instance of gvim (or vim), then do:
1. `set kp=:Nman`
2. `itest<esc>`
3. `K`

Expected output is the man buffer for `test`, instead I get this error message:

```
:! :Nman 'test'
[No write since last change]
zsh:1: command not found: :Nman

shell returned 127
```

**Comment by nhooyr** [comment]
@lervag ah its neovim specific. Vim only uses external commands for that option, whereas neovim lets you use vim commands. I added a note to the readme, thanks.

I think you should just create a global mapping yourself.

**Comment by lervag** [comment]
Yes, I've already used a mapping to solve the problem. I just thought you should know. The readme file should be updated, I think.

**Comment by nhooyr** [comment]
I did update it.

**Comment by lervag** [comment]
Haha, I didn't check (you should mark commits with issue tags).

**Comment by nhooyr** [comment]
@lervag I always forget, dammit. Will do it next time.
