### ISSUE TITLE
shell integration (maybe) broken with zsh

### ISSUE THREAD

**Issue by aktau** [nhooyr/neoman.vim#11]
Pasting the following in my .zshrc:

``` bash
function _nman {
    local l=$#
    local page=(${@:1:$l-1})
    if [[ -z "$page" ]]; then
        echo "What manual page do you want?"
        return
    fi
    local tmp=$IFS
    IFS=$'\n' out=($(command man -w ${page[@]} 2>&1))
    local code=$?
    IFS=$tmp
    if [[ ${#out[@]} > 1 ]]; then
        echo "Too many manpages"
        return
    elif [[ $code != 0 ]]; then
        echo "No manual entry for ${page[*]}"
        return
    fi
    if [[ -z $NVIM_LISTEN_ADDRESS ]]; then
        command nvim -c "${@: -1} ${page[*]}"
    else
        nvr --remote-send "<c-n>" -c "${@: -1} ${page[*]}"
    fi
}
function nman {
    _nman "$@" 'Nman'
}
function nman! {
    _nman "$@" 'Nman!'
}
```

I get:

```
$ nman write
_nman:2: unknown file attribute: i
```

It does work in bash, however. I have zsh 5.0.x and bash 4.3.

The plugin is awesome, thanks!

**Comment by nhooyr** [comment]
@aktau I'm not sure what's wrong, exact same piece of code works fine for me. Can you set all of zsh's options to default and try?

**Comment by aktau** [comment]
I'm not sure how to set zsh's options to default really. I've done this:

nman.sh

``` zsh
# Same script as before (define functions)

# Execute
nman "$@"
```

And then I run:

``` sh
$ zsh ./nman.sh write
_nman:2: unknown file attribute: i
```

I think that when called thusly, zsh doesn't load anything special...

**Comment by aktau** [comment]
I think one of the problems may be the use of `local` together with the array. See http://stackoverflow.com/questions/14917501/local-arrays-in-zsh

Now I'm really wondering: how come this works for you? What version of zsh are you using?

As indicated on that SO page, the solution could be something like:

``` diff
- local page=(${@:1:$l-1})
+ local -a page
+ page=(${@:1:$l-1})
```

This works for me on my zsh.

**Comment by psprint** [comment]
The syntax that allows to set array together with declaring it is available starting from zsh-5.2. As ataku wrote, other Zsh versions need 2 lines of code

**Comment by nhooyr** [comment]
@aktau Ah, IRC to the rescue.

the syntax local a=( ... ) is allowed starting from zsh-5.2

I'm using 5.2, thats why I never noticed. I'll edit it thanks!

**Comment by aktau** [comment]
Thanks!
