### ISSUE TITLE
add option to disable/customize default mappings

### ISSUE THREAD

**Issue by ninrod** [nhooyr/neoman.vim#12]
I for one find the `q` mapping particularly annoying. Let me state my case. 
1. `q` is not a fast bind because you'll always have binds `q:` and `q/`. So you have to press `q` and wait a sec before it quicks in. 
2. I use `q/` a lot. inside a neoman buffer. I search a lot inside `man` buffers so I want to skim through previous search patterns. As neoman binds `q` to `:q`, I get screwed quite a lot.

I love your plugin by the way. Great work.

**Comment by nhooyr** [comment]
Thanks.
The setting already exists.

``` vim
let g:no_neoman_maps = 1
```
