### ISSUE TITLE
Cannot close last window

### ISSUE THREAD

**Issue by lervag** [nhooyr/neoman.vim#16]
The `q` mapping seems to be mapped to `<c-w>c`. When trying to close the last window, Vim yields error 444 "Cannot close last window". Perhaps instead one should map `nnoremap <buffer> q :q`?

**Comment by nhooyr** [comment]
@lervag before last nights PR, it was `:q` but over on the PR at neovim, @justinmk said

```
This is not the same as <C-W>c. The old mapping was intentional. Can't change this.

The <nowait> was also intentional...
```

Then again, I still think `:q` does make more sense. I'll change it back in neoman but leave it in the neovim PR.

**Comment by lervag** [comment]
Interesting. I don't get why we "Can't change this". Well, who cares. I'm glad you reverted in the main plugin! It doesn't make sense to me to make `q` map to `close` instead of `quit`.

**Comment by justinmk** [comment]
>  I don't get why we "Can't change this".

Because the plugin should not quit the entire editor. _No other_ stock plugin does this.

**Comment by nhooyr** [comment]
@justinmk but in the context of a pager, it should close the entire editor. It's more intuitive. Every vim man page plugin adds that `:q` mapping. https://github.com/jez/vim-superman, https://github.com/lambdalisue/vim-manpager, http://vim.wikia.com/wiki/Using_vim_as_a_man-page_viewer_under_Unix, https://github.com/vim-utils/vim-man. If people are gonna add it anyway, why not include it as the default.

**Comment by justinmk** [comment]
> but in the context of a pager, it should close the entire editor.

If someone does `:Man foo` in an editing session (not using vim as a pager), it should not close the editor. If there's a way to reliably detect that situation with less than 2 lines of code, then it would make sense.

**Comment by nhooyr** [comment]
@justinmk that would open in a new tab though, so it wouldn't really matter. It'd just close the tab.

**Comment by justinmk** [comment]
No, users may switch to a previously-opened `man://` buffer in the current (single) tab. Not to mention the window feature you added.

**Comment by lervag** [comment]
How about something like:

``` vim
nnoremap <nowait><expr><buffer> q
  \ len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) > 0
  \ ? ':bwipeout<cr>' : ':quit<cr>'
```

**Comment by nhooyr** [comment]
@justinmk fair enough.

I think lervag's solution is a nice middle ground. But we should change `:bwipeout` to `:close`.

**Comment by lervag** [comment]
@nhooyr No, `:close` will not work, because it works on windows. The point here is to not close Vim if there are any buffers remaining. Perhaps one needs more advanced stuff than this if people use tabs (I generally don't).

**Comment by nhooyr** [comment]
@lervag I don't understand. `:close` will close the window, leave the buffer, and not close vim. That's the behaviour we want if there are more buffers remaining.

**Comment by lervag** [comment]
@nhooyr No: If the current window is the last window, then `:close` will give error 444 similar to the origin of this issue. Thus, if I start Vim, open some file, then do `:Nman something` with Nman opening in the current window, then I have: 1 open file that is hidden (implied `bufhidden`), one open Nman page, and a single window. `:close` will not work, because it can't close the last window. `:bwipeout`, however, will kill the Nman buffer as expected.

**Comment by nhooyr** [comment]
@lervag ah gotcha. but `:bwipeout` is may also cause some confusion. If I type `:Nman printf` and then split to see two parts of the same manpage, hitting q with your mapping would result in both being closed, I think `:close` might be more intuitive here.

**Comment by nhooyr** [comment]
@lervag if you use neovim, checkout neovim/neovim#4449, it automatically maps `q` correctly based on whether neovim was opened as a pager.

**Comment by lervag** [comment]
Thanks! Looks interesting, but I still haven't jumped the ship on Vim yet. I'm considering it, but it will take some time to reconfigure and get used to it. Besides, I use gvim alot, and as far as I understand, there is still not real neovim gvim alternative.

**Comment by nhooyr** [comment]
You should try https://github.com/equalsraf/neovim-qt

**Comment by lervag** [comment]
Thanks for the suggestion! I'll definately look into this some more when I get the time.
