### ISSUE TITLE
the last file completion is automatically selected

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/neoman.vim#17]
This is weird, if you type `:Nman ./<TAB>` the very last file that can be completed is automatically selected. Why?

Code is very simple. 

https://github.com/nhooyr/neoman.vim/blob/master/autoload/neoman.vim#L214-L215

@Corax26 this is the bug I found before, remember that commented out code in the completion function? Although that was for the man pages, not sure whats wrong here.

**Comment by ghost** [comment]
Hmm I'm confused, for me `:Nman ./<Tab>` just shows me the normal file completion results (for the current directory), nothing surprising.

**Comment by nhooyr** [comment]
https://asciinema.org/a/4l9y7410gntjbjiq0fb8ekolk

See how when I just do `:Nman pri<TAB>` it only shows the completions, it doesn't complete anything? Whereas `:Nman ./<TAB>` completes the last one for some reason?

**Comment by ghost** [comment]
Well that's interesting, with vim 7.4.1529 I don't get the same behaviour! Probably something specific to Neovim, or maybe something config-dependant? I tried with an empty vimrc (so default `'completeopt'`), it completes the first one as normal.

**Comment by nhooyr** [comment]
@Corax26 yea its with `completeopt=list,full` (whoops meant `wildmode`). Its in vim and neovim. I'll make a bug report soon, I don't think there is anything wrong with the code.

**Comment by ghost** [comment]
Got it, you meant `wildmode=list,full` though, not `completeopt`. Now, this is getting really weird. With the default setting (`full`), the first result is returned, makes sense. With my personal setting (`longest,list,full`), I get the full list, makes sense. No idea why `list,full` in particular results in this weird behaviour, that might very well be a bug...

**Comment by nhooyr** [comment]
Yes, sorry I meant wildmode. Will post a bug report soon. I'll leave this issue open for now.

**Comment by ghost** [comment]
All right, good move, please cc me in the bug report (or post the link here) :)

**Comment by nhooyr** [comment]
I've created the neovim issue at neovim/neovim#5173 and vim issue at vim/vim#969
