### ISSUE TITLE
"_nman:10: number expected" error with Neovim shell integration

### ISSUE THREAD

**Issue by tpict** [nhooyr/neoman.vim#18]
I get the error `_nman:10: number expected` for any man page with `neovim.zsh` sourced. The error occurs in both plain zsh and zsh running inside Neovim. If a page is specified, e.g. 1, I get the error `_nman:10: bad pattern: page=(1`. The :Nman command works just great, and shell integration works for `vim.zsh`.

**Comment by nhooyr** [comment]
No idea what's wrong. Can you try using zsh with default options?

**Comment by tpict** [comment]
I get the same error with the default configuration. Running zsh 5.2 stable on OS X 10.11.3

**Comment by nhooyr** [comment]
@motdef I'm using zsh 5.2 on OSX 10.11.3 as well. You are on the latest version of neoman right?

**Comment by tpict** [comment]
I am, just cloned it this morning. Very strange...

**Comment by nhooyr** [comment]
@motdef IRC provided the answer, I'll update the script. test it and let me know.

**Comment by tpict** [comment]
Perfect, thank you!
