### ISSUE TITLE
Can not jump to printf(3)

### ISSUE THREAD

**Issue by tracyone** [nhooyr/neoman.vim#19]
ubuntu 14.04.3 i686 

vim version:7.4 1558 huge version

nvim version:0.1.3-dev   201603101534+2362+17~ubuntu 14.4.1

every time I execute following command,it jump to printf(1) instead of printf(3)

``` vim
:Nman 3 printf
```

or 

``` vim
:Nman printf(3)
```

it do have printf manual in man 3

man 3 printf

**Comment by nhooyr** [comment]
@tracyone latest version of neoman correct?

Does `:Man 3 printf` work correctly?

**Comment by tracyone** [comment]
no `:Man` command.

``` shell
man 3 printf
```

work correctly in shell

**Comment by nhooyr** [comment]
@tracyone Try with neovim, it should have the `:Man` command. vim has it too, but you have to load it with `:runtime! ftplugin/man.vim`

**Comment by nhooyr** [comment]
And can you show me the output of `man -w 3 printf`

**Comment by tracyone** [comment]
``` vim
:Man 3 printf
```

work correctly in  vim after add `runtime! ftplugin/man.vim` and neovim.

---

``` shell
man -w 3 printf
/usr/share/man/man3/printf.3.gz
```

and

``` shell
man -w 1 printf
/usr/share/man/man1/printf.1.gz
```

**Comment by nhooyr** [comment]
Great, thanks. I'll look into it in a few hours, don't have my laptop on me.
@tracyone and just to reiterate because you didn't explicitly answer, you are on the latest neoman?

**Comment by tracyone** [comment]
sorry.

Yes,I just updated the `neoman.vim`. And the issue still exists.

**Comment by tracyone** [comment]
a test for this issue.

File minimal_vimrc

``` vim
let $VIMFILES = $HOME.'/.vim'                                                                                                                                                
 set nocompatible                                                                                                                                                             
 set nu rnu                                                                                                                                                                   
 set wildmenu                                                                                                                                                                 
 set wildmode=longest,full
let &rtp=&rtp.",".$VIMFILES."/bundle/neoman.vim/"                                                                                                                            
 runtime 'plugin/neoman.vim'                                                                                                                                                  
 runtime 'autoload/neoman.vim'                                                                                                                                                
 filetype plugin indent on
syntax on 
```

``` shell
vim -u minimal_vimrc
nvim -u minimal_vimrc
```

the issue still exist

**Comment by nhooyr** [comment]
https://github.com/nhooyr/neoman.vim/blob/master/autoload/neoman.vim#L46

On that line, can you add `echom page.'('.sect.')'`? What does it output?

**Comment by tracyone** [comment]
the output message of `:Nman 3 printf` after add `echom page.'('.sect.')'` in that line is:

printf(3)

**Comment by nhooyr** [comment]
what about https://github.com/nhooyr/neoman.vim/blob/master/autoload/neoman.vim#L54

**Comment by tracyone** [comment]
result is printf(gz)

![xxx](https://cloud.githubusercontent.com/assets/4246425/13875166/3a89ca24-ed37-11e5-9e7f-814102561093.gif)

**Comment by nhooyr** [comment]
@tracyone https://github.com/nhooyr/neoman.vim/blob/master/autoload/neoman.vim#L120

That if statement should be triggering. try removing the `\n` at the end.

**Comment by tracyone** [comment]
@nhooyr it work.
message:
printf(3)
printf(3)

**Comment by nhooyr** [comment]
@tracyone fantastic, when I get my hands on my laptop, I'll update.
