### ISSUE TITLE
[Request] Use an external program to generate man pages

### ISSUE THREAD

**Issue by cazador481** [nhooyr/neoman.vim#21]
I would love the ability to have nman to specify an external man page generator depending on the file type that I am working on.  For example if I am using perl I would like it to run perldoc -o nroff <keyword>.
Bonus points if you can keep nman knowing that I used perldoc to generate so I can jump from within one generated man page to another.

**Comment by nhooyr** [comment]
I'm not sure exactly what you mean. I don't know much about perldoc. Can you elaborate? Why can't we just use `man`?

**Comment by cazador481** [comment]
In the case of perldoc, the man pages don't exist.  So perldoc is creating them.

Here is a function that I have created to wrap perldoc w/ nman . 

``` perl
function! Perldoc(Method)
    let tmp=tempname()
    call system("perldoc -onroff -d ".tmp." ".a:Method)
    if (v:shell_error)
        echom "Could not find docs for ".a:Method
        return
    endif
    " silent exec "!perldoc -onroff -d ".tmp a:Method
    exec "Nman ".tmp
    exec "file man://".a:Method
    call delete(tmp)
endfunc

```

And here is the function that I used to allow jumping from one perldoc to another

``` perl
function! Get_pagePerldoc(bang, editcmd, ...) abort
  if a:0 > 2
    call s:error('too many arguments')
    return
  elseif a:0 == 2
    let sect = a:000[0]
    let page = a:000[1]
  else
    " fpage is a string like 'printf(2)' or just 'printf'
    " if no argument, use the word under the cursor
    let fpage = get(a:000, 0, expand('<cWORD>'))
    if empty(fpage)
      call s:error('no WORD under cursor')
      return
    endif
    call Perldoc(expand('<cWORD>'))
  endif
endfunction
```

**Comment by nhooyr** [comment]
@cazador481 I understand now. I'll look into it further later, but I'm open to PRs.

**Comment by nhooyr** [comment]
I'm not going to be working on this plugin anymore. I've fixed many bugs and refactored the code and it is now included as the default man plugin in neovim. If you would still like this, please open an issue at https://github.com/neovim/neovim/issues/new
