### ISSUE TITLE
Strange display issues

### ISSUE THREAD

**Issue by adambiggs** [nhooyr/neoman.vim#22]
I just installed this plugin using the latest version of NeoVim (built from master), but for some reason the display is pretty messed up for me...

![screen shot 2016-03-22 at 1 07 13 pm](https://cloud.githubusercontent.com/assets/857229/13966364/492bb25e-f02f-11e5-8092-b5ecf20c6db5.png)

**Comment by nhooyr** [comment]
does `:Man` work fine? Also can you remove this [line](https://github.com/nhooyr/neoman.vim/blob/master/autoload/neoman.vim#L135) and then take a screenshot.

**Comment by adambiggs** [comment]
`:Man` works:

![screen shot 2016-03-22 at 1 30 41 pm](https://cloud.githubusercontent.com/assets/857229/13967013/535b5830-f032-11e5-99ed-2c330c297622.png)

But `:Nman` still doesn't, even after commenting out the line you mentioned. Although the weird characters are slightly different now:

![screen shot 2016-03-22 at 1 31 53 pm](https://cloud.githubusercontent.com/assets/857229/13967057/8f5664a6-f032-11e5-8115-4bbbfcbcbc2a.png)

**Comment by nhooyr** [comment]
@adambiggs this is really weird, that line is supposed to remove all of the `^H` characters. Do you have anything odd about your setup? Could you try duplicating that line, e.g. doing it twice and see what happens?

Or try the this after that line `execute "silent! keepjumps %substitute,\b,,g"`

**Comment by nhooyr** [comment]
Closing due to no further information.

**Comment by kdeal** [comment]
I encountered the same issue and found out it was due to `set gdefault`. This causes `%substitute,\b,,g` to only replace the first occurrence instead of all occurrence in a line.

**Comment by nhooyr** [comment]
I've actually fixed that bug in the neovim man.vim

I don't use vim (or neovim) anymore so I haven't bothered porting the neovim man.vim over. Here is the PR for the fix for this https://github.com/neovim/neovim/pull/5182

If you could please open a PR to fix this, it would be much appreciated. However, if possible, you should try neovim as man.vim is officially supported there (and its entirely based on this plugin).
