### ISSUE TITLE
[Request] Support man -k

### ISSUE THREAD

**Issue by rgrinberg** [nhooyr/neoman.vim#23]
Doing something like `:NmanSearch x` would translate to running `man -k x` and loading the results into the quickfix. Naturally, clicking any of the elements in the quickfix would navigate to the man page using `:Nman`. I think such a feature would be incredibly nice.

**Comment by nhooyr** [comment]
I'm busy with school and another project right now. But this feature does sound good, I'll look into it soon.

**Comment by nhooyr** [comment]
I'm not going to be working on this plugin anymore. I've fixed many bugs and refactored the code and it is now included as the default man plugin in neovim. If you would still like this, please open an issue at https://github.com/neovim/neovim/issues/new
