### ISSUE TITLE
receive a error saying changing a readonly file

### ISSUE THREAD

**Issue by hiecaq** [nhooyr/neoman.vim#25]
I'm using OS X Sierra with neovim, every time I call `Nman` or jump into a man page tag will get this warning:

```
Error detected while processing function neoman#get_page[30]..<SNR>73_read_page:
line    5:W10: Warning: Changing a readonly file
```

Also, although command like `:Nman printf(3)` works, `:Nman 3 printf` will enter the `printf(1)` page.

**Comment by nhooyr** [comment]
You shouldn't need to use this plugin. The default man plugin in neovim is a ***much*** better version of neoman. If you still have the issue, open it on the neovim github and I'll help you there.
