### ISSUE TITLE
error info releate

### ISSUE THREAD

**Issue by tracyone** [nhooyr/neoman.vim#26]
```bash
man 3 read
No manual entry for read in section 3
```

But

```vim
Nman 3 read
```

will open read(2) automatically

another example

```bash
man 3 open 
No manual entry for open in section 3
```

```vim
Nman 3 open
```

it will show openvt(1).

I am a C programming developer,I only care about manual 2 and 3

I want to query the function in manual 2 and 3 when I am editting C source file .

I am expecting a error occour when the function is not in manual 2 or 3 ,so i can handle it and find the function in other place (like linux kernel's manpage).

Nman 3  must be failed if the keyword is not in the specified section.

**Comment by nhooyr** [comment]
I'm sorry, I do not maintain this plugin anymore. I maintain the default manpage plugin in neovim which is an improved version of this plugin. From your dotfiles, it looks like you do use neovim so try on there and if you still have an issue, file it here https://github.com/neovim/neovim/issues/new
