### ISSUE TITLE
display issue start from command line

### ISSUE THREAD

**Issue by lookforit** [nhooyr/neoman.vim#28]
I launched  `man grep`  from terminal after set .zshrc as guidance :
```shell
export MANPAGER="vim -c'set ft=neoman' -"  #change nvim to vim 
```

But I got the weird display:
![default](https://user-images.githubusercontent.com/1892462/28667041-5a318e10-72fc-11e7-9fa7-f6f1167a4f86.png)

So why?

**Comment by nhooyr** [comment]
I have not been maintaining this plugin. I've been maintaining the neovim man.vim. I've fixed this bug there. See https://github.com/neovim/neovim/pull/6033/files

Using neovim would fix your problem. If you'd like to remain on vim, could you please open a PR on this plugin similar to my fix for neovim's man.vim?

You'd have to update the regexes used on these two lines https://github.com/nhooyr/neoman.vim/pull/27/files with the regex used in the linked neovim PR.

**Comment by lookforit** [comment]
OK.
I already sent the PR,pls check.

**Comment by nhooyr** [comment]
Thank you.
