### ISSUE TITLE
use different shell func name for neovim and vim.

### ISSUE THREAD

**Issue by wsdjeg** [nhooyr/neoman.vim#3]
I using neovim and vim at the same time ,also with same vimrc,so please use different shell func names for neovim and vim,thanks!
just line `_nvim_nman` and `_vim_nman`

**Comment by nhooyr** [comment]
So `_nman` to `_nvim_nman` and `_vim_nman`?

**Comment by wsdjeg** [comment]
yes,but I don't why this show me error

``` sh
nman!(){
}
```

**Comment by nhooyr** [comment]
@wsdjeg using bash? I have a feeling thats the problem. I'll try to get it to work with bash soon.

**Comment by nhooyr** [comment]
I didn't rename it, if you want to do renaming, you can very easily do it yourself. Those functions just really serve as examples.

**Comment by wsdjeg** [comment]
yes ,thanks for fixing
