### ISSUE TITLE
By default split?

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/neoman.vim#4]
I've been thinking that we should by default split, and behave similarly to the builtin help command. Except if you use a bang, it opens in the current window just like it does now.

@lervag what do you think? (sorry I have no one else to discuss this with)

**Comment by sunaku** [comment]
Emulating `:help` behavior sounds like a good thing to do. :+1:

**Comment by sunaku** [comment]
Actually, you should emulate `:Man` which opens the result in a new tab in NeoVim.

**Comment by nhooyr** [comment]
@sunaku i find that super annoying. Thats part of the reason I created this plugin. I much prefer the way `:help` works to `:Man`.

**Comment by sunaku** [comment]
Ah, thanks for explaining. :sweat_smile:

**Comment by lervag** [comment]
I agree, it should split similar to `:help` by default. I would say bang should not open in current window, it should instead open in current `Neoman` window if any exists, else open in a split window.

You could add an option that specifies how it splits. This would allow @sunaku and others to instead open in new tab.

**Comment by nhooyr** [comment]
I'll add that all of that with mappings for splitting. Should I rename the command `Neoman` to simply `Nman`?

**Comment by lervag** [comment]
Both names work fine for me (if I end up using this plugin, I will use mappings). `Neoman` sounds better, whereas `Nman` is shorter.

**Comment by nhooyr** [comment]
Alright for now I just renamed it to `Nman` and added a notice on the readme.

**Comment by lervag** [comment]
Sounds good to me.

**Comment by nhooyr** [comment]
What do you guys think of the new commands now?

**Comment by lervag** [comment]
I think it works very nicely, thanks.

**Comment by nhooyr** [comment]
Great.
