### ISSUE TITLE
Elaborate on how to create a custom command

### ISSUE THREAD

**Issue by rgrinberg** [nhooyr/neoman.vim#9]
The docs mention that something like:

``` vim
:vsplit | Nman! 3 printf
```

is enough

But if I define that as a command, I won't have the cool tab completion. Anyway I can recover that?

**Comment by nhooyr** [comment]
@rgrinberg 

``` vim
command! -bang -complete=customlist,neoman#Complete -nargs=* Vnman vsplit | call neoman#get_page(<bang>0, <f-args>)

```

**Comment by nhooyr** [comment]
I'll update the readme as well, thanks, though first a few changes.

**Comment by nhooyr** [comment]
@rgrinberg I've updated the docs and commands now. What do you think?

**Comment by rgrinberg** [comment]
that's perfect, thanks.
